### Making Student with God Data
POST http://localhost:8080/add
Content-Type: application/json

{
  "firstName": "{{$random.alphabetic(8)}}",
  "lastName": "Matheis",
  "email": "{{$random.email}}",
  "eContact": "1495954059"
}

### Making Student with Bad Data
POST http://localhost:8080/add
Content-Type: application/json

{
  "firstName": "",
  "lastName": "Matheis",
  "email": "{{$random.email}}",
  "eContact": "999"
}


###
PATCH http://localhost:8080/update/1
Content-Type: application/json

{
  "email": "new.Email3@email.com",
  "eContact": "3425325436"
}

<> 2024-07-17T084925.200.txt
<> 2024-07-17T083901.200.txt

###
GET http://localhost:8080/all

> {%
    client.test("Response status code is 200", function () {
        client.assert(response.status === 200)
    });
%}

###
DELETE http://localhost:8080/delete/42

###
GET http://localhost:8080/findByName/Matheis

>{%

 %}